#!/usr/bin/env bash

####################
#  CHECK FOR ROOT  #
####################

if [ "$(id -u)" -ne 0 ]; then echo " $red Please run as root.$clr ex. sudo rollback" >&2; exit; fi
##########################################################

### Help #############
if [ "$1" = "-h" ]; then
snapper-rollback -h
exit
fi
######################

if [ -x "$(command -v snapper)" ]; then
mount -o subvolid=5 /dev/mapper/cryptroot /mnt/btrfsroot
  snapper list 2>/dev/null
fi

if [ $? -ne 0 ] || ! [ -x "$(command -v snapper)" ]; then
grep -Er '<date>|<type>' /mnt/btrfsroot/@snapshots/*/info.xml | awk -F '</[^}]*>' '{print $1 $2}' | sed 's/[i][^:]*//' | sed 's/[/][^s]*//' | sed 's/[<][^>]*//' | tac -r | more
fi

echo
read -p "Enter the snapshot number to restore : " snap

echo -e "\nYou selected snapshot: '$snap'"
echo
echo "'snapper-rollback $1 $snap' command will be run."
echo
echo "Type 'CONFIRM' to continue or 'ENTER' to quit."
echo
mount /dev/nvme0n1p2 /efi
snapper-rollback $1 $snap
umount /efi
